# Generated by Django 6.0.4 on 2026-04-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_client_par_boutique',
        ),
        migrations.RemoveConstraint(
            model_name='produit',
            name='unique_produit_par_boutique',
        ),
        migrations.RenameIndex(
            model_name='messagelog',
            new_name='boutiques_m_boutiqu_656412_idx',
            old_name='boutiques_m_boutiqu_idx',
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('boutique', 'telephone')},
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('boutique', 'nom')},
        ),
    ]
