# Generated by Django 6.0.4 on 2026-04-17 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0007_boutique_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.PositiveIntegerField(default=0, help_text='Frais de livraison en FCFA, figés au moment de la commande'),
        ),
        migrations.AlterField(
            model_name='boutique',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identifiant URL de la boutique (ex: teranga-shop)', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex : Dakar Plateau, Banlieue...', max_length=100)),
                ('frais', models.PositiveIntegerField(default=0, help_text='Frais de livraison en FCFA (0 = gratuit)')),
                ('actif', models.BooleanField(default=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_livraison', to='boutiques.boutique')),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['frais', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='zone_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='boutiques.zonelivraison'),
        ),
    ]
