# Generated by Django 6.0.4 on 2026-04-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0008_zones_livraison_frais_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)")),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='boutiques.boutique')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
                'unique_together': {('boutique', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='boutiques.categorie'),
        ),
    ]
