# Generated by Django 6.0.1 on 2026-04-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0009_categorie_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='description',
            field=models.TextField(blank=True, help_text='Description courte visible sur la vitrine (horaires, adresse, infos pratiques…)'),
        ),
    ]
