# Generated by Django 6.0.1 on 2026-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0012_boutique_proprietaire_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='qr_code_wave',
            field=models.ImageField(blank=True, help_text='QR code Wave à scanner pour payer', null=True, upload_to='qr_codes/'),
        ),
    ]
