# Generated by Django 6.0.1 on 2026-04-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0013_boutique_qr_code_wave'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='wa_config_validee',
            field=models.BooleanField(default=False, help_text='True si le bot WhatsApp fonctionne correctement', verbose_name='Configuration WhatsApp validée'),
        ),
    ]
