# Generated by Django 6.0.1 on 2026-05-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0014_boutique_wa_config_validee'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='infobip_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration du code de validation'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='infobip_code_validation',
            field=models.CharField(blank=True, help_text='Code envoyé par SMS pour valider le numéro', max_length=6, verbose_name='Code de validation SMS'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='infobip_config_en_cours',
            field=models.BooleanField(default=False, help_text='True si le commerçant est en train de configurer son numéro', verbose_name='Configuration Infobip en cours'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='infobip_display_name',
            field=models.CharField(blank=True, help_text='Nom affiché sur WhatsApp (ex: SALMON SHOP)', max_length=100, verbose_name="Nom d'affichage WhatsApp"),
        ),
        migrations.AddField(
            model_name='boutique',
            name='infobip_sender',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp configuré dans Infobip pour cette boutique', max_length=20, verbose_name='Numéro Infobip sender'),
        ),
    ]
