# Generated by Django 6.0.1 on 2026-05-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0015_boutique_infobip_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='conversation_etat',
            field=models.JSONField(blank=True, default=dict, help_text="Stocke l'état de la conversation WhatsApp du commerçant", verbose_name='État de conversation'),
        ),
    ]
